package com.example.project.Airport;
import java.util.ArrayList;
import java.util.List;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public int getTotalRevenue() {
        int totalRevenue = 0;
        
        for (Flight flight : allFlights) {
            int passengers = Math.min(flight.getNumPassengers(), flight.getCapacity());
            totalRevenue += passengers * flight.getPrice();
        }
        
        return totalRevenue;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int removedPassengers = 0;
        ArrayList<Flight> remainingFlights = new ArrayList<>();
        
        for (Flight flight : allFlights) {
            if (flight.getNumPassengers() >= 0.2 * flight.getCapacity()) {
                remainingFlights.add(flight);
            } else {
                removedPassengers += flight.getNumPassengers();
            }
        }
        
        allFlights = remainingFlights;
        return removedPassengers;
    }
}
